import { User, UserRole } from '@/types/auth.types';
import { Event, EventClient } from '@/types/events';

// Mock User Roles
export const ROLES: UserRole[] = [
  { id: 1, name: 'admin', displayName: 'Administrador' },
  { id: 2, name: 'socio', displayName: 'Socio' },
  { id: 3, name: 'encargado_compras', displayName: 'Encargado de Compras' },
  { id: 4, name: 'servicio', displayName: 'Personal de Servicio' },
];

// Mock Users (Demo mode)
export interface MockUser extends User {
  password: string;
  assignedEventIds?: number[];
}

export const DEMO_USERS: MockUser[] = [
  {
    id: 1,
    email: 'admin@eventhub.com',
    password: 'admin123',
    name: 'Admin',
    last_name: 'Sistema',
    role: ROLES[0],
    phone: '+51 999 888 777',
    address: 'Oficina Central',
    document_type: 'DNI',
    document_number: '12345678',
    birth_date: '1990-01-01',
    gender: 'Masculino',
    nationality: 'Perú',
    created_at: new Date('2024-01-01'),
    updated_at: new Date('2024-01-01'),
    assignedEventIds: [],
    is_verified: true,
    is_blocked: false,
  },
  {
    id: 2,
    email: 'coordinador@eventhub.com',
    password: 'coord123',
    name: 'Coordinador',
    last_name: 'General',
    role: ROLES[3], // servicio role que se usará para coordinadores
    phone: '+51 999 777 666',
    address: 'Lima',
    document_type: 'DNI',
    document_number: '23456789',
    birth_date: '1985-06-15',
    gender: 'Masculino',
    nationality: 'Perú',
    created_at: new Date('2024-01-05'),
    updated_at: new Date('2024-01-05'),
    assignedEventIds: [],
    is_verified: true,
    is_blocked: false,
  },
  {
    id: 3,
    email: 'compras@eventhub.com',
    password: 'compras123',
    name: 'Encargado',
    last_name: 'de Compras',
    role: ROLES[2],
    phone: '+51 999 666 555',
    address: 'Lima',
    document_type: 'DNI',
    document_number: '34567890',
    birth_date: '1992-03-20',
    gender: 'Masculino',
    nationality: 'Perú',
    created_at: new Date('2024-01-10'),
    updated_at: new Date('2024-01-10'),
    assignedEventIds: [],
    is_verified: true,
    is_blocked: false,
  },
];

// Mock Clients
export const MOCK_CLIENTS: EventClient[] = [
  { id: 1, name: 'Tech Corp', email: 'contact@techcorp.com', phone: '+34 912 345 678', company: 'Tech Corp S.L.' },
  { id: 2, name: 'María González', email: 'maria@email.com', phone: '+52 55 1234 5678', company: 'Eventos MG' },
  { id: 3, name: 'Carlos Ruiz', email: 'carlos@email.com', phone: '+54 11 2345 6789' },
];

// Mock Events - VACÍO, los eventos se crearán en localStorage
export const MOCK_EVENTS: Event[] = [];

export const MOCK_DASHBOARD_DATA: Record<number, any> = {
  1: { // Admin
    totalEvents: 25,
    activeEvents: 8,
    totalRevenue: 145800,
    totalExpenses: 87200,
  },
  2: { // Socio - Same as admin
    totalEvents: 25,
    activeEvents: 8,
    totalRevenue: 145800,
    totalExpenses: 87200,
  },
};

// Función para inicializar eventos de ejemplo en localStorage (solo la primera vez)
export function initializeSampleEvents() {
  const hasInitialized = localStorage.getItem('events_initialized');
  
  // Solo inicializar si no se ha hecho antes
  if (!hasInitialized) {
    console.log('🎯 Inicializando 10 eventos de ejemplo con fechas correctas...');
    
    const sampleEvents: Event[] = [
      // EVENTOS COMPLETADOS (pasados - antes de octubre 2025)
      // 1. Mayo - Completado
      {
        id: 1001,
        name: 'Boda de Rosa y Miguel',
        description: 'Ceremonia y recepción en jardín',
        type: 'boda',
        status: 'completed',
        date: '2025-05-15',
        endDate: '2025-05-15',
        location: 'Local Solaz',
        venue: 'Local Solaz',
        attendees: 180,
        maxAttendees: 200,
        client: {
          id: 1,
          name: 'Rosa',
          last_name: 'García',
          phone: '+51 999 111 222',
          email: 'rosa@email.com',
          address: 'Lima Centro',
          document_type: 'DNI',
          document_number: '98765432',
        },
        serviceType: 'con_comida',
        foodDetails: {
          cantidadDePlatos: 180,
          tipoMenu: 'buffet',
          precioPorPlato: 65,
        },
        financial: {
          budget: 15000,
          totalIncome: 15000,
          totalExpenses: 8500,
          balance: 6500,
          advancePayment: 7500,
          pendingPayment: 0,
        },
        contract: {
          tipoContrato: 'privado',
          precioTotal: 15000,
          pagoAdelantado: 7500,
          saldoPendiente: 0,
          fechaFirma: '2025-04-15',
        },
        assignedServiceUsers: [2, 3],
        payments: [],
        expenses: [],
        decoration: [],
        furniture: [],
        staff: [],
        timeline: [],
        tags: [],
        createdBy: 1,
        createdByName: 'Admin Sistema',
        createdAt: '2025-04-15',
        updatedAt: '2025-05-16',
        imageUrl: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=800',
      },
      // 2. Junio - Completado
      {
        id: 1002,
        name: 'Quinceañera de Valeria',
        description: 'Fiesta de 15 años con tema princesa',
        type: 'quince_años',
        status: 'completed',
        date: '2025-06-28',
        endDate: '2025-06-28',
        location: 'Local Praga',
        venue: 'Local Praga',
        attendees: 135,
        maxAttendees: 150,
        client: {
          id: 2,
          name: 'Valeria',
          last_name: 'Torres',
          phone: '+51 999 333 444',
          email: 'valeria@email.com',
          address: 'San Isidro',
          document_type: 'DNI',
          document_number: '87654321',
        },
        serviceType: 'con_comida',
        foodDetails: {
          cantidadDePlatos: 135,
          tipoMenu: 'criollo',
          precioPorPlato: 55,
        },
        financial: {
          budget: 12000,
          totalIncome: 12000,
          totalExpenses: 6800,
          balance: 5200,
          advancePayment: 6000,
          pendingPayment: 0,
        },
        contract: {
          tipoContrato: 'privado',
          precioTotal: 12000,
          pagoAdelantado: 6000,
          saldoPendiente: 0,
          fechaFirma: '2025-05-28',
        },
        assignedServiceUsers: [2],
        payments: [],
        expenses: [],
        decoration: [],
        furniture: [],
        staff: [],
        timeline: [],
        tags: [],
        createdBy: 1,
        createdByName: 'Admin Sistema',
        createdAt: '2025-05-28',
        updatedAt: '2025-06-29',
        imageUrl: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800',
      },
      // 3. Julio - Completado
      {
        id: 1003,
        name: 'Aniversario Tech Solutions',
        description: 'Celebración 10 años de la empresa',
        type: 'corporativo',
        status: 'completed',
        date: '2025-07-10',
        endDate: '2025-07-10',
        location: 'Local Solaz',
        venue: 'Local Solaz',
        attendees: 95,
        maxAttendees: 100,
        client: {
          id: 3,
          name: 'Tech Solutions',
          last_name: 'SAC',
          phone: '+51 999 555 666',
          email: 'contacto@techsolutions.com',
          address: 'San Borja',
          document_type: 'RUC',
          document_number: '20123456789',
        },
        serviceType: 'con_comida',
        foodDetails: {
          cantidadDePlatos: 95,
          tipoMenu: 'gourmet',
          precioPorPlato: 75,
        },
        financial: {
          budget: 10000,
          totalIncome: 10000,
          totalExpenses: 5200,
          balance: 4800,
          advancePayment: 5000,
          pendingPayment: 0,
        },
        contract: {
          tipoContrato: 'corporativo',
          precioTotal: 10000,
          pagoAdelantado: 5000,
          saldoPendiente: 0,
          fechaFirma: '2025-06-10',
        },
        assignedServiceUsers: [3],
        payments: [],
        expenses: [],
        decoration: [],
        furniture: [],
        staff: [],
        timeline: [],
        tags: [],
        createdBy: 1,
        createdByName: 'Admin Sistema',
        createdAt: '2025-06-10',
        updatedAt: '2025-07-11',
        imageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800',
      },
      // 4. Agosto - Completado
      {
        id: 1004,
        name: 'Cumpleaños de Carlos (50 años)',
        description: 'Fiesta sorpresa de cumpleaños',
        type: 'cumpleaños',
        status: 'completed',
        date: '2025-08-20',
        endDate: '2025-08-20',
        location: 'Local Praga',
        venue: 'Local Praga',
        attendees: 75,
        maxAttendees: 80,
        client: {
          id: 4,
          name: 'María',
          last_name: 'López',
          phone: '+51 999 777 888',
          email: 'maria.lopez@email.com',
          address: 'Miraflores',
          document_type: 'DNI',
          document_number: '45678901',
        },
        serviceType: 'con_comida',
        foodDetails: {
          cantidadDePlatos: 75,
          tipoMenu: 'buffet',
          precioPorPlato: 60,
        },
        financial: {
          budget: 8000,
          totalIncome: 8000,
          totalExpenses: 4300,
          balance: 3700,
          advancePayment: 4000,
          pendingPayment: 0,
        },
        contract: {
          tipoContrato: 'privado',
          precioTotal: 8000,
          pagoAdelantado: 4000,
          saldoPendiente: 0,
          fechaFirma: '2025-07-20',
        },
        assignedServiceUsers: [2, 3],
        payments: [],
        expenses: [],
        decoration: [],
        furniture: [],
        staff: [],
        timeline: [],
        tags: [],
        createdBy: 1,
        createdByName: 'Admin Sistema',
        createdAt: '2025-07-20',
        updatedAt: '2025-08-21',
        imageUrl: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800',
      },
      // 5. Septiembre - Completado
      {
        id: 1005,
        name: 'Quinceañera de Isabella',
        description: 'Fiesta temática vintage',
        type: 'quince_años',
        status: 'completed',
        date: '2025-09-10',
        endDate: '2025-09-10',
        location: 'Local Praga',
        venue: 'Local Praga',
        attendees: 110,
        maxAttendees: 120,
        client: {
          id: 5,
          name: 'Patricia',
          last_name: 'Flores',
          phone: '+51 999 888 999',
          email: 'patricia.flores@email.com',
          address: 'Barranco',
          document_type: 'DNI',
          document_number: '56789012',
        },
        serviceType: 'con_comida',
        foodDetails: {
          cantidadDePlatos: 110,
          tipoMenu: 'buffet',
          precioPorPlato: 58,
        },
        financial: {
          budget: 11000,
          totalIncome: 11000,
          totalExpenses: 5900,
          balance: 5100,
          advancePayment: 5500,
          pendingPayment: 0,
        },
        contract: {
          tipoContrato: 'privado',
          precioTotal: 11000,
          pagoAdelantado: 5500,
          saldoPendiente: 0,
          fechaFirma: '2025-08-10',
        },
        assignedServiceUsers: [2],
        payments: [],
        expenses: [],
        decoration: [],
        furniture: [],
        staff: [],
        timeline: [],
        tags: [],
        createdBy: 1,
        createdByName: 'Admin Sistema',
        createdAt: '2025-08-10',
        updatedAt: '2025-09-11',
        imageUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=800',
      },
      
      // EVENTOS CONFIRMADOS (futuros - octubre en adelante)
      // 6. Noviembre - Confirmado
      {
        id: 1006,
        name: 'Boda de Andrea y Javier',
        description: 'Ceremonia y banquete de lujo',
        type: 'boda',
        status: 'confirmed',
        date: '2025-11-15',
        endDate: '2025-11-15',
        location: 'Local Praga',
        venue: 'Local Praga',
        attendees: 220,
        maxAttendees: 250,
        client: {
          id: 6,
          name: 'Andrea',
          last_name: 'Mendoza',
          phone: '+51 999 444 555',
          email: 'andrea.mendoza@email.com',
          address: 'La Molina',
          document_type: 'DNI',
          document_number: '34567890',
        },
        serviceType: 'con_comida',
        foodDetails: {
          cantidadDePlatos: 220,
          tipoMenu: 'gourmet',
          precioPorPlato: 85,
        },
        financial: {
          budget: 25000,
          totalIncome: 12500,
          totalExpenses: 0,
          balance: 12500,
          advancePayment: 12500,
          pendingPayment: 12500,
        },
        contract: {
          tipoContrato: 'privado',
          precioTotal: 25000,
          pagoAdelantado: 12500,
          saldoPendiente: 12500,
          fechaFirma: '2025-10-15',
        },
        assignedServiceUsers: [2, 3],
        payments: [],
        expenses: [],
        decoration: [],
        furniture: [],
        staff: [],
        timeline: [],
        tags: [],
        createdBy: 1,
        createdByName: 'Admin Sistema',
        createdAt: '2025-10-15',
        updatedAt: '2025-10-15',
        imageUrl: 'https://images.unsplash.com/photo-1519167758481-83f29da8a36f?w=800',
      },
      // 7. Noviembre - Confirmado
      {
        id: 1007,
        name: 'Bautizo de Sofía',
        description: 'Ceremonia religiosa y recepción',
        type: 'otro',
        status: 'confirmed',
        date: '2025-11-05',
        endDate: '2025-11-05',
        location: 'Local Solaz',
        venue: 'Local Solaz',
        attendees: 60,
        maxAttendees: 70,
        client: {
          id: 7,
          name: 'Ana',
          last_name: 'Ramírez',
          phone: '+51 999 222 333',
          email: 'ana.ramirez@email.com',
          address: 'Surco',
          document_type: 'DNI',
          document_number: '23456789',
        },
        serviceType: 'con_comida',
        foodDetails: {
          cantidadDePlatos: 60,
          tipoMenu: 'criollo',
          precioPorPlato: 50,
        },
        financial: {
          budget: 5500,
          totalIncome: 2750,
          totalExpenses: 0,
          balance: 2750,
          advancePayment: 2750,
          pendingPayment: 2750,
        },
        contract: {
          tipoContrato: 'privado',
          precioTotal: 5500,
          pagoAdelantado: 2750,
          saldoPendiente: 2750,
          fechaFirma: '2025-10-05',
        },
        assignedServiceUsers: [2],
        payments: [],
        expenses: [],
        decoration: [],
        furniture: [],
        staff: [],
        timeline: [],
        tags: [],
        createdBy: 1,
        createdByName: 'Admin Sistema',
        createdAt: '2025-10-05',
        updatedAt: '2025-10-05',
        imageUrl: 'https://images.unsplash.com/photo-1464347744102-11db6282f854?w=800',
      },
      // 8. Diciembre - Confirmado
      {
        id: 1008,
        name: 'Reunión Anual Directorio',
        description: 'Almuerzo ejecutivo',
        type: 'corporativo',
        status: 'confirmed',
        date: '2025-12-05',
        endDate: '2025-12-05',
        location: 'Local Solaz',
        venue: 'Local Solaz',
        attendees: 40,
        maxAttendees: 50,
        client: {
          id: 8,
          name: 'Inversiones',
          last_name: 'Peru SAC',
          phone: '+51 999 666 777',
          email: 'contacto@inversiones.pe',
          address: 'San Isidro',
          document_type: 'RUC',
          document_number: '20987654321',
        },
        serviceType: 'con_comida',
        foodDetails: {
          cantidadDePlatos: 40,
          tipoMenu: 'gourmet',
          precioPorPlato: 90,
        },
        financial: {
          budget: 6000,
          totalIncome: 3000,
          totalExpenses: 0,
          balance: 3000,
          advancePayment: 3000,
          pendingPayment: 3000,
        },
        contract: {
          tipoContrato: 'corporativo',
          precioTotal: 6000,
          pagoAdelantado: 3000,
          saldoPendiente: 3000,
          fechaFirma: '2025-11-05',
        },
        assignedServiceUsers: [3],
        payments: [],
        expenses: [],
        decoration: [],
        furniture: [],
        staff: [],
        timeline: [],
        tags: [],
        createdBy: 1,
        createdByName: 'Admin Sistema',
        createdAt: '2025-11-05',
        updatedAt: '2025-11-05',
        imageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800',
      },
      // 9. Diciembre - Confirmado
      {
        id: 1009,
        name: 'Cumpleaños de Mateo (7 años)',
        description: 'Fiesta temática superhéroes',
        type: 'cumpleaños',
        status: 'confirmed',
        date: '2025-12-15',
        endDate: '2025-12-15',
        location: 'Local Solaz',
        venue: 'Local Solaz',
        attendees: 50,
        maxAttendees: 60,
        client: {
          id: 9,
          name: 'Laura',
          last_name: 'Vega',
          phone: '+51 999 123 456',
          email: 'laura.vega@email.com',
          address: 'Pueblo Libre',
          document_type: 'DNI',
          document_number: '67890123',
        },
        serviceType: 'con_comida',
        foodDetails: {
          cantidadDePlatos: 50,
          tipoMenu: 'criollo',
          precioPorPlato: 45,
        },
        financial: {
          budget: 4500,
          totalIncome: 2250,
          totalExpenses: 0,
          balance: 2250,
          advancePayment: 2250,
          pendingPayment: 2250,
        },
        contract: {
          tipoContrato: 'privado',
          precioTotal: 4500,
          pagoAdelantado: 2250,
          saldoPendiente: 2250,
          fechaFirma: '2025-11-15',
        },
        assignedServiceUsers: [2, 3],
        payments: [],
        expenses: [],
        decoration: [],
        furniture: [],
        staff: [],
        timeline: [],
        tags: [],
        createdBy: 1,
        createdByName: 'Admin Sistema',
        createdAt: '2025-11-15',
        updatedAt: '2025-11-15',
        imageUrl: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800',
      },
      // 10. Enero 2026 - Confirmado
      {
        id: 1010,
        name: 'Graduación Promoción 2026',
        description: 'Ceremonia y cena de gala',
        type: 'otro',
        status: 'confirmed',
        date: '2026-01-20',
        endDate: '2026-01-20',
        location: 'Local Praga',
        venue: 'Local Praga',
        attendees: 150,
        maxAttendees: 160,
        client: {
          id: 10,
          name: 'Colegio Santa',
          last_name: 'Rosa',
          phone: '+51 999 321 654',
          email: 'eventos@santarosa.edu.pe',
          address: 'Jesús María',
          document_type: 'RUC',
          document_number: '20456789012',
        },
        serviceType: 'con_comida',
        foodDetails: {
          cantidadDePlatos: 150,
          tipoMenu: 'gourmet',
          precioPorPlato: 70,
        },
        financial: {
          budget: 13000,
          totalIncome: 6500,
          totalExpenses: 0,
          balance: 6500,
          advancePayment: 6500,
          pendingPayment: 6500,
        },
        contract: {
          tipoContrato: 'corporativo',
          precioTotal: 13000,
          pagoAdelantado: 6500,
          saldoPendiente: 6500,
          fechaFirma: '2025-12-20',
        },
        assignedServiceUsers: [2, 3],
        payments: [],
        expenses: [],
        decoration: [],
        furniture: [],
        staff: [],
        timeline: [],
        tags: [],
        createdBy: 1,
        createdByName: 'Admin Sistema',
        createdAt: '2025-12-20',
        updatedAt: '2025-12-20',
        imageUrl: 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=800',
      },
    ];

    // Guardar eventos en localStorage
    localStorage.setItem('demo_events', JSON.stringify(sampleEvents));
    localStorage.setItem('events_initialized', 'true');
    
    // Actualizar assignedEventIds de los usuarios
    const users = JSON.parse(localStorage.getItem('demo_users') || JSON.stringify(DEMO_USERS));
    const updatedUsers = users.map((u: any) => {
      if (u.id === 2) { // Coordinador
        return { ...u, assignedEventIds: [1001, 1002, 1004, 1005, 1006, 1007, 1009, 1010] };
      } else if (u.id === 3) { // Encargado de Compras
        return { ...u, assignedEventIds: [1001, 1003, 1004, 1006, 1008, 1009, 1010] };
      }
      return u;
    });
    localStorage.setItem('demo_users', JSON.stringify(updatedUsers));
    
    console.log('✅ 10 eventos de ejemplo inicializados correctamente');
    console.log('📅 5 eventos completados (mayo-septiembre 2025)');
    console.log('📅 5 eventos confirmados (noviembre 2025 - enero 2026)');
  }
}