import { User, UserRole } from '@/types/auth.types';
import { Event, EventClient } from '@/types/events';

// Mock User Roles
export const ROLES: UserRole[] = [
  { id: 1, name: 'admin', displayName: 'Administrador' },
  { id: 2, name: 'socio', displayName: 'Socio' },
  { id: 3, name: 'encargado_compras', displayName: 'Encargado de Compras' },
  { id: 4, name: 'servicio', displayName: 'Personal de Servicio' },
];

// Mock Users (Demo mode)
export interface MockUser extends User {
  password: string;
  assignedEventIds?: number[];
}

export const DEMO_USERS: MockUser[] = [
  {
    id: 1,
    email: 'admin@eventhub.com',
    password: 'admin123',
    name: 'Admin',
    last_name: 'Sistema',
    role: ROLES[0],
    phone: '+51 999 888 777',
    address: 'Oficina Central',
    document_type: 'DNI',
    document_number: '12345678',
    birth_date: '1990-01-01',
    gender: 'Masculino',
    nationality: 'Perú',
    created_at: new Date('2024-01-01'),
    updated_at: new Date('2024-01-01'),
    assignedEventIds: [],
  },
  {
    id: 2,
    email: 'socio@eventhub.com',
    password: 'socio123',
    name: 'Carlos',
    last_name: 'Socio',
    role: ROLES[1],
    phone: '+51 999 777 666',
    address: 'Av. Principal 456',
    document_type: 'DNI',
    document_number: '23456789',
    birth_date: '1985-06-15',
    gender: 'Masculino',
    nationality: 'Perú',
    created_at: new Date('2024-01-05'),
    updated_at: new Date('2024-01-05'),
    assignedEventIds: [],
  },
  {
    id: 3,
    email: 'compras@eventhub.com',
    password: 'compras123',
    name: 'María',
    last_name: 'Compras',
    role: ROLES[2],
    phone: '+51 999 666 555',
    address: 'Calle Secundaria 789',
    document_type: 'DNI',
    document_number: '34567890',
    birth_date: '1992-03-20',
    gender: 'Femenino',
    nationality: 'Perú',
    created_at: new Date('2024-01-10'),
    updated_at: new Date('2024-01-10'),
    assignedEventIds: [],
  },
  {
    id: 4,
    email: 'juan@eventhub.com',
    password: 'juan123',
    name: 'Juan',
    last_name: 'Pérez',
    role: ROLES[3],
    phone: '+51 999 555 444',
    address: 'Jr. Los Pinos 321',
    document_type: 'DNI',
    document_number: '45678901',
    birth_date: '1995-09-10',
    gender: 'Masculino',
    nationality: 'Perú',
    created_at: new Date('2024-01-15'),
    updated_at: new Date('2024-01-15'),
    assignedEventIds: [1, 2, 3], // Asignado a eventos ficticios
  },
];

// Mock Clients
export const MOCK_CLIENTS: EventClient[] = [
  { id: 1, name: 'Tech Corp', email: 'contact@techcorp.com', phone: '+34 912 345 678', company: 'Tech Corp S.L.' },
  { id: 2, name: 'María González', email: 'maria@email.com', phone: '+52 55 1234 5678', company: 'Eventos MG' },
  { id: 3, name: 'Carlos Ruiz', email: 'carlos@email.com', phone: '+54 11 2345 6789' },
];

// Mock Events - EVENTOS FICTICIOS PARA MÉTRICAS
export const MOCK_EVENTS: Event[] = [
  // Evento del mes pasado (completado)
  {
    id: 1,
    name: 'Boda de Rosa y Miguel',
    description: 'Ceremonia y recepción en jardín',
    type: 'boda',
    status: 'completed',
    date: '2025-05-15',
    endDate: '2025-05-15',
    location: 'Salón Jardín Principal',
    venue: 'Local de Eventos',
    attendees: 150,
    maxAttendees: 200,
    client: {
      id: 1,
      name: 'Rosa',
      last_name: 'García',
      phone: '+51 999 111 222',
      email: 'rosa@email.com',
      address: 'Lima Centro',
      document_type: 'DNI',
      document_number: '98765432',
    },
    serviceType: 'con_comida',
    foodDetails: {
      cantidadDePlatos: 150,
      tipoMenu: 'buffet',
      precioPorPlato: 65,
    },
    financial: {
      budget: 15000,
      totalIncome: 15000,
      totalExpenses: 8500,
      balance: 6500,
      advancePayment: 7500,
      pendingPayment: 0,
    },
    contract: {
      tipoContrato: 'privado',
      precioTotal: 15000,
      pagoAdelantado: 7500,
      saldoPendiente: 0,
      fechaFirma: '2025-04-15',
    },
    assignedServiceUsers: [4],
    payments: [],
    expenses: [],
    decoration: [],
    furniture: [],
    staff: [],
    timeline: [],
    tags: [],
    createdBy: 1,
    createdByName: 'Admin Sistema',
    createdAt: '2025-04-15',
    updatedAt: '2025-05-16',
    imageUrl: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=800',
  },
  // Evento de este mes (confirmado - próximo)
  {
    id: 2,
    name: 'Quinceañera de Valeria',
    description: 'Fiesta de 15 años con tema princesa',
    type: 'quince_años',
    status: 'confirmed',
    date: '2025-06-22',
    endDate: '2025-06-22',
    location: 'Salón Imperial',
    venue: 'Local de Eventos',
    attendees: 120,
    maxAttendees: 150,
    client: {
      id: 2,
      name: 'Valeria',
      last_name: 'Torres',
      phone: '+51 999 333 444',
      email: 'valeria@email.com',
      address: 'San Isidro',
      document_type: 'DNI',
      document_number: '87654321',
    },
    serviceType: 'con_comida',
    foodDetails: {
      cantidadDePlatos: 120,
      tipoMenu: 'criollo',
      precioPorPlato: 55,
    },
    financial: {
      budget: 12000,
      totalIncome: 6000,
      totalExpenses: 2500,
      balance: 3500,
      advancePayment: 6000,
      pendingPayment: 6000,
    },
    contract: {
      tipoContrato: 'privado',
      precioTotal: 12000,
      pagoAdelantado: 6000,
      saldoPendiente: 6000,
      fechaFirma: '2025-05-22',
    },
    assignedServiceUsers: [4],
    payments: [],
    expenses: [],
    decoration: [],
    furniture: [],
    staff: [],
    timeline: [],
    tags: [],
    createdBy: 1,
    createdByName: 'Admin Sistema',
    createdAt: '2025-05-22',
    updatedAt: '2025-05-22',
    imageUrl: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800',
  },
  // Evento del mes que viene (confirmado)
  {
    id: 3,
    name: 'Cumpleaños Corporativo Tech Solutions',
    description: 'Aniversario 10 años de la empresa',
    type: 'corporativo',
    status: 'confirmed',
    date: '2025-07-10',
    endDate: '2025-07-10',
    location: 'Salón Ejecutivo',
    venue: 'Local de Eventos',
    attendees: 80,
    maxAttendees: 100,
    client: {
      id: 3,
      name: 'Tech Solutions',
      last_name: 'SAC',
      phone: '+51 999 555 666',
      email: 'contacto@techsolutions.com',
      address: 'San Borja',
      document_type: 'RUC',
      document_number: '20123456789',
    },
    serviceType: 'con_comida',
    foodDetails: {
      cantidadDePlatos: 80,
      tipoMenu: 'gourmet',
      precioPorPlato: 75,
    },
    financial: {
      budget: 10000,
      totalIncome: 5000,
      totalExpenses: 0,
      balance: 5000,
      advancePayment: 5000,
      pendingPayment: 5000,
    },
    contract: {
      tipoContrato: 'corporativo',
      precioTotal: 10000,
      pagoAdelantado: 5000,
      saldoPendiente: 5000,
      fechaFirma: '2025-06-10',
    },
    assignedServiceUsers: [4],
    payments: [],
    expenses: [],
    decoration: [],
    furniture: [],
    staff: [],
    timeline: [],
    tags: [],
    createdBy: 1,
    createdByName: 'Admin Sistema',
    createdAt: '2025-06-10',
    updatedAt: '2025-06-10',
    imageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800',
  },
];

export const MOCK_DASHBOARD_DATA: Record<number, any> = {
  1: { // Admin
    totalEvents: 25,
    activeEvents: 8,
    totalRevenue: 145800,
    totalExpenses: 87200,
  },
  2: { // Socio - Same as admin
    totalEvents: 25,
    activeEvents: 8,
    totalRevenue: 145800,
    totalExpenses: 87200,
  },
};